product:
  table:
    host: database
    port: 5432
    database: postgres
    username: postgres
    password: POSTGRES_PASSWORD

cache:
  elems:
    threshold: 500
    remains_after_clean: 250
  buckets_amount: 8
  backup_interval: 30m

http-server:
  port: 8000

nats-server:
  host: nats:4222
  subjects:
    product: event.product
    user: event.user