product:
  table:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: POSTGRES_PASSWORD

user:
  table:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: POSTGRES_PASSWORD

cache:
  threshold: 250
  buckets_amount: 8

http-server:
  port: 8000

nats-server:
  host: 127.0.0.1:4222
  subjects:
    product: event.product
    user: event.user