services:
  main:
    build:
      dockerfile: Dockerfile
    command: ./main
    ports:
      - 8000:8000
    depends_on:
      - database
      - nats
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - cache_backup:/var/lib/cache/data
      - database_backup:/var/lib/database/data

  database:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  nats:
    restart: always
    image: nats:latest
    ports:
      - 4222:4222

volumes:
  database_data:
  cache_backup:
  database_backup: