services:
  main:
    build:
      dockerfile: Dockerfile
    command: ./main
    ports:
      - 8000:8000
    depends_on:
      - database
      - nats
      - prometheus
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - cache_backup:/var/lib/cache/data

  database:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  nats:
    restart: always
    image: nats:latest
    ports:
      - 4222:4222

  prometheus:
    restart: always
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  database_data:
  cache_backup:
  prometheus_data:
  grafana-storage: