database:
  host: "localhost"
  port: 5432
  database: "postgres"
  username: "postgres"
  password: "POSTGRES_PASSWORD"
cache:
  cleanup_interval: 60s
http_server:
  port: "8085"
nats_server:
  host: "127.0.0.1"
  port: "4222"
  subject: "handlers.producthandler"